/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDividendDistributor,
  IDividendDistributorInterface,
} from "../../../src/interfaces/IDividendDistributor";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "investor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DividendClaimed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "partition",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "snapshotBlock",
        type: "uint256",
      },
    ],
    name: "DividendDistributed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DividendReclaimed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
    ],
    name: "claimDividend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
    ],
    name: "claimableDividend",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "partition",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "paymentToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "totalAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "claimDuration",
        type: "uint256",
      },
    ],
    name: "distributeDividend",
    outputs: [
      {
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
    ],
    name: "getDistribution",
    outputs: [
      {
        components: [
          {
            internalType: "bytes32",
            name: "partition",
            type: "bytes32",
          },
          {
            internalType: "address",
            name: "paymentToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "totalAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "snapshotBlock",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "claimDeadline",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "distributedAt",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "finalized",
            type: "bool",
          },
        ],
        internalType: "struct IDividendDistributor.Distribution",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "investor",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
    ],
    name: "hasClaimed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "distributionId",
        type: "bytes32",
      },
    ],
    name: "reclaimUnclaimed",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDividendDistributor__factory {
  static readonly abi = _abi;
  static createInterface(): IDividendDistributorInterface {
    return new Interface(_abi) as IDividendDistributorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDividendDistributor {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IDividendDistributor;
  }
}
