/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IComplianceInterface extends Interface {
  getFunction(
    nameOrSignature: "canTransfer" | "isVerified" | "transferred"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ComplianceChecked" | "KYCStatusUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferred",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferred",
    data: BytesLike
  ): Result;
}

export namespace ComplianceCheckedEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    amount: BigNumberish,
    allowed: boolean
  ];
  export type OutputTuple = [
    from: string,
    to: string,
    amount: bigint,
    allowed: boolean
  ];
  export interface OutputObject {
    from: string;
    to: string;
    amount: bigint;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCStatusUpdatedEvent {
  export type InputTuple = [account: AddressLike, verified: boolean];
  export type OutputTuple = [account: string, verified: boolean];
  export interface OutputObject {
    account: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ICompliance extends BaseContract {
  connect(runner?: ContractRunner | null): ICompliance;
  waitForDeployment(): Promise<this>;

  interface: IComplianceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canTransfer: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "view"
  >;

  isVerified: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  transferred: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferred"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ComplianceChecked"
  ): TypedContractEvent<
    ComplianceCheckedEvent.InputTuple,
    ComplianceCheckedEvent.OutputTuple,
    ComplianceCheckedEvent.OutputObject
  >;
  getEvent(
    key: "KYCStatusUpdated"
  ): TypedContractEvent<
    KYCStatusUpdatedEvent.InputTuple,
    KYCStatusUpdatedEvent.OutputTuple,
    KYCStatusUpdatedEvent.OutputObject
  >;

  filters: {
    "ComplianceChecked(address,address,uint256,bool)": TypedContractEvent<
      ComplianceCheckedEvent.InputTuple,
      ComplianceCheckedEvent.OutputTuple,
      ComplianceCheckedEvent.OutputObject
    >;
    ComplianceChecked: TypedContractEvent<
      ComplianceCheckedEvent.InputTuple,
      ComplianceCheckedEvent.OutputTuple,
      ComplianceCheckedEvent.OutputObject
    >;

    "KYCStatusUpdated(address,bool)": TypedContractEvent<
      KYCStatusUpdatedEvent.InputTuple,
      KYCStatusUpdatedEvent.OutputTuple,
      KYCStatusUpdatedEvent.OutputObject
    >;
    KYCStatusUpdated: TypedContractEvent<
      KYCStatusUpdatedEvent.InputTuple,
      KYCStatusUpdatedEvent.OutputTuple,
      KYCStatusUpdatedEvent.OutputObject
    >;
  };
}
