/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IDividendDistributor {
  export type DistributionStruct = {
    partition: BytesLike;
    paymentToken: AddressLike;
    totalAmount: BigNumberish;
    snapshotBlock: BigNumberish;
    claimDeadline: BigNumberish;
    distributedAt: BigNumberish;
    finalized: boolean;
  };

  export type DistributionStructOutput = [
    partition: string,
    paymentToken: string,
    totalAmount: bigint,
    snapshotBlock: bigint,
    claimDeadline: bigint,
    distributedAt: bigint,
    finalized: boolean
  ] & {
    partition: string;
    paymentToken: string;
    totalAmount: bigint;
    snapshotBlock: bigint;
    claimDeadline: bigint;
    distributedAt: bigint;
    finalized: boolean;
  };
}

export interface IDividendDistributorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimDividend"
      | "claimableDividend"
      | "distributeDividend"
      | "getDistribution"
      | "hasClaimed"
      | "reclaimUnclaimed"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DividendClaimed"
      | "DividendDistributed"
      | "DividendReclaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimDividend",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableDividend",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeDividend",
    values: [BytesLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDistribution",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reclaimUnclaimed",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeDividend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reclaimUnclaimed",
    data: BytesLike
  ): Result;
}

export namespace DividendClaimedEvent {
  export type InputTuple = [
    distributionId: BytesLike,
    investor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    distributionId: string,
    investor: string,
    amount: bigint
  ];
  export interface OutputObject {
    distributionId: string;
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendDistributedEvent {
  export type InputTuple = [
    distributionId: BytesLike,
    partition: BytesLike,
    paymentToken: AddressLike,
    totalAmount: BigNumberish,
    snapshotBlock: BigNumberish
  ];
  export type OutputTuple = [
    distributionId: string,
    partition: string,
    paymentToken: string,
    totalAmount: bigint,
    snapshotBlock: bigint
  ];
  export interface OutputObject {
    distributionId: string;
    partition: string;
    paymentToken: string;
    totalAmount: bigint;
    snapshotBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DividendReclaimedEvent {
  export type InputTuple = [distributionId: BytesLike, amount: BigNumberish];
  export type OutputTuple = [distributionId: string, amount: bigint];
  export interface OutputObject {
    distributionId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDividendDistributor extends BaseContract {
  connect(runner?: ContractRunner | null): IDividendDistributor;
  waitForDeployment(): Promise<this>;

  interface: IDividendDistributorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimDividend: TypedContractMethod<
    [distributionId: BytesLike],
    [void],
    "nonpayable"
  >;

  claimableDividend: TypedContractMethod<
    [investor: AddressLike, distributionId: BytesLike],
    [bigint],
    "view"
  >;

  distributeDividend: TypedContractMethod<
    [
      partition: BytesLike,
      paymentToken: AddressLike,
      totalAmount: BigNumberish,
      claimDuration: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getDistribution: TypedContractMethod<
    [distributionId: BytesLike],
    [IDividendDistributor.DistributionStructOutput],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [investor: AddressLike, distributionId: BytesLike],
    [boolean],
    "view"
  >;

  reclaimUnclaimed: TypedContractMethod<
    [distributionId: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimDividend"
  ): TypedContractMethod<[distributionId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableDividend"
  ): TypedContractMethod<
    [investor: AddressLike, distributionId: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "distributeDividend"
  ): TypedContractMethod<
    [
      partition: BytesLike,
      paymentToken: AddressLike,
      totalAmount: BigNumberish,
      claimDuration: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDistribution"
  ): TypedContractMethod<
    [distributionId: BytesLike],
    [IDividendDistributor.DistributionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [investor: AddressLike, distributionId: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "reclaimUnclaimed"
  ): TypedContractMethod<[distributionId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "DividendClaimed"
  ): TypedContractEvent<
    DividendClaimedEvent.InputTuple,
    DividendClaimedEvent.OutputTuple,
    DividendClaimedEvent.OutputObject
  >;
  getEvent(
    key: "DividendDistributed"
  ): TypedContractEvent<
    DividendDistributedEvent.InputTuple,
    DividendDistributedEvent.OutputTuple,
    DividendDistributedEvent.OutputObject
  >;
  getEvent(
    key: "DividendReclaimed"
  ): TypedContractEvent<
    DividendReclaimedEvent.InputTuple,
    DividendReclaimedEvent.OutputTuple,
    DividendReclaimedEvent.OutputObject
  >;

  filters: {
    "DividendClaimed(bytes32,address,uint256)": TypedContractEvent<
      DividendClaimedEvent.InputTuple,
      DividendClaimedEvent.OutputTuple,
      DividendClaimedEvent.OutputObject
    >;
    DividendClaimed: TypedContractEvent<
      DividendClaimedEvent.InputTuple,
      DividendClaimedEvent.OutputTuple,
      DividendClaimedEvent.OutputObject
    >;

    "DividendDistributed(bytes32,bytes32,address,uint256,uint256)": TypedContractEvent<
      DividendDistributedEvent.InputTuple,
      DividendDistributedEvent.OutputTuple,
      DividendDistributedEvent.OutputObject
    >;
    DividendDistributed: TypedContractEvent<
      DividendDistributedEvent.InputTuple,
      DividendDistributedEvent.OutputTuple,
      DividendDistributedEvent.OutputObject
    >;

    "DividendReclaimed(bytes32,uint256)": TypedContractEvent<
      DividendReclaimedEvent.InputTuple,
      DividendReclaimedEvent.OutputTuple,
      DividendReclaimedEvent.OutputObject
    >;
    DividendReclaimed: TypedContractEvent<
      DividendReclaimedEvent.InputTuple,
      DividendReclaimedEvent.OutputTuple,
      DividendReclaimedEvent.OutputObject
    >;
  };
}
