/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IInvestorRegistry {
  export type InvestorInfoStruct = {
    investorType: BigNumberish;
    registeredAt: BigNumberish;
    expiresAt: BigNumberish;
  };

  export type InvestorInfoStructOutput = [
    investorType: bigint,
    registeredAt: bigint,
    expiresAt: bigint
  ] & { investorType: bigint; registeredAt: bigint; expiresAt: bigint };

  export type PartitionLimitStruct = {
    maxHolding: BigNumberish;
    currentHolding: BigNumberish;
    lockedUntil: BigNumberish;
  };

  export type PartitionLimitStructOutput = [
    maxHolding: bigint,
    currentHolding: bigint,
    lockedUntil: bigint
  ] & { maxHolding: bigint; currentHolding: bigint; lockedUntil: bigint };
}

export interface IInvestorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canAcceptTransfer"
      | "getInvestorInfo"
      | "getPartitionLimit"
      | "isRegistered"
      | "register"
      | "revoke"
      | "setLockup"
      | "updateHolding"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HoldingUpdated"
      | "InvestorRegistered"
      | "InvestorRevoked"
      | "LockupSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canAcceptTransfer",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInvestorInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPartitionLimit",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike, BigNumberish, BigNumberish, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLockup",
    values: [AddressLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateHolding",
    values: [AddressLike, BytesLike, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "canAcceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInvestorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPartitionLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setLockup", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateHolding",
    data: BytesLike
  ): Result;
}

export namespace HoldingUpdatedEvent {
  export type InputTuple = [
    investor: AddressLike,
    partition: BytesLike,
    newHolding: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    partition: string,
    newHolding: bigint
  ];
  export interface OutputObject {
    investor: string;
    partition: string;
    newHolding: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestorRegisteredEvent {
  export type InputTuple = [investor: AddressLike, investorType: BigNumberish];
  export type OutputTuple = [investor: string, investorType: bigint];
  export interface OutputObject {
    investor: string;
    investorType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestorRevokedEvent {
  export type InputTuple = [investor: AddressLike, reason: BytesLike];
  export type OutputTuple = [investor: string, reason: string];
  export interface OutputObject {
    investor: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockupSetEvent {
  export type InputTuple = [
    investor: AddressLike,
    partition: BytesLike,
    lockedUntil: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    partition: string,
    lockedUntil: bigint
  ];
  export interface OutputObject {
    investor: string;
    partition: string;
    lockedUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IInvestorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IInvestorRegistry;
  waitForDeployment(): Promise<this>;

  interface: IInvestorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canAcceptTransfer: TypedContractMethod<
    [investor: AddressLike, partition: BytesLike, amount: BigNumberish],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;

  getInvestorInfo: TypedContractMethod<
    [investor: AddressLike],
    [IInvestorRegistry.InvestorInfoStructOutput],
    "view"
  >;

  getPartitionLimit: TypedContractMethod<
    [investor: AddressLike, partition: BytesLike],
    [IInvestorRegistry.PartitionLimitStructOutput],
    "view"
  >;

  isRegistered: TypedContractMethod<[investor: AddressLike], [boolean], "view">;

  register: TypedContractMethod<
    [
      investor: AddressLike,
      investorType: BigNumberish,
      maxHolding: BigNumberish,
      partitions: BytesLike[],
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  revoke: TypedContractMethod<
    [investor: AddressLike, reason: BytesLike],
    [void],
    "nonpayable"
  >;

  setLockup: TypedContractMethod<
    [investor: AddressLike, partition: BytesLike, lockedUntil: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateHolding: TypedContractMethod<
    [
      investor: AddressLike,
      partition: BytesLike,
      amount: BigNumberish,
      isIncrease: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canAcceptTransfer"
  ): TypedContractMethod<
    [investor: AddressLike, partition: BytesLike, amount: BigNumberish],
    [[boolean, string] & { allowed: boolean; reason: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInvestorInfo"
  ): TypedContractMethod<
    [investor: AddressLike],
    [IInvestorRegistry.InvestorInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPartitionLimit"
  ): TypedContractMethod<
    [investor: AddressLike, partition: BytesLike],
    [IInvestorRegistry.PartitionLimitStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[investor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      investor: AddressLike,
      investorType: BigNumberish,
      maxHolding: BigNumberish,
      partitions: BytesLike[],
      expiresAt: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<
    [investor: AddressLike, reason: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLockup"
  ): TypedContractMethod<
    [investor: AddressLike, partition: BytesLike, lockedUntil: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateHolding"
  ): TypedContractMethod<
    [
      investor: AddressLike,
      partition: BytesLike,
      amount: BigNumberish,
      isIncrease: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "HoldingUpdated"
  ): TypedContractEvent<
    HoldingUpdatedEvent.InputTuple,
    HoldingUpdatedEvent.OutputTuple,
    HoldingUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "InvestorRegistered"
  ): TypedContractEvent<
    InvestorRegisteredEvent.InputTuple,
    InvestorRegisteredEvent.OutputTuple,
    InvestorRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "InvestorRevoked"
  ): TypedContractEvent<
    InvestorRevokedEvent.InputTuple,
    InvestorRevokedEvent.OutputTuple,
    InvestorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "LockupSet"
  ): TypedContractEvent<
    LockupSetEvent.InputTuple,
    LockupSetEvent.OutputTuple,
    LockupSetEvent.OutputObject
  >;

  filters: {
    "HoldingUpdated(address,bytes32,uint256)": TypedContractEvent<
      HoldingUpdatedEvent.InputTuple,
      HoldingUpdatedEvent.OutputTuple,
      HoldingUpdatedEvent.OutputObject
    >;
    HoldingUpdated: TypedContractEvent<
      HoldingUpdatedEvent.InputTuple,
      HoldingUpdatedEvent.OutputTuple,
      HoldingUpdatedEvent.OutputObject
    >;

    "InvestorRegistered(address,uint8)": TypedContractEvent<
      InvestorRegisteredEvent.InputTuple,
      InvestorRegisteredEvent.OutputTuple,
      InvestorRegisteredEvent.OutputObject
    >;
    InvestorRegistered: TypedContractEvent<
      InvestorRegisteredEvent.InputTuple,
      InvestorRegisteredEvent.OutputTuple,
      InvestorRegisteredEvent.OutputObject
    >;

    "InvestorRevoked(address,bytes32)": TypedContractEvent<
      InvestorRevokedEvent.InputTuple,
      InvestorRevokedEvent.OutputTuple,
      InvestorRevokedEvent.OutputObject
    >;
    InvestorRevoked: TypedContractEvent<
      InvestorRevokedEvent.InputTuple,
      InvestorRevokedEvent.OutputTuple,
      InvestorRevokedEvent.OutputObject
    >;

    "LockupSet(address,bytes32,uint256)": TypedContractEvent<
      LockupSetEvent.InputTuple,
      LockupSetEvent.OutputTuple,
      LockupSetEvent.OutputObject
    >;
    LockupSet: TypedContractEvent<
      LockupSetEvent.InputTuple,
      LockupSetEvent.OutputTuple,
      LockupSetEvent.OutputObject
    >;
  };
}
