/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IOracle {
  export type OracleDataStruct = {
    dataType: BytesLike;
    value: BigNumberish;
    timestamp: BigNumberish;
    signature: BytesLike;
  };

  export type OracleDataStructOutput = [
    dataType: string,
    value: bigint,
    timestamp: bigint,
    signature: string
  ] & { dataType: string; value: bigint; timestamp: bigint; signature: string };
}

export interface IOracleInterface extends Interface {
  getFunction(nameOrSignature: "getLatestData" | "verify"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DataUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "getLatestData",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [IOracle.OracleDataStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getLatestData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export namespace DataUpdatedEvent {
  export type InputTuple = [
    dataType: BytesLike,
    value: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    dataType: string,
    value: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    dataType: string;
    value: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IOracle extends BaseContract {
  connect(runner?: ContractRunner | null): IOracle;
  waitForDeployment(): Promise<this>;

  interface: IOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLatestData: TypedContractMethod<
    [dataType: BytesLike],
    [IOracle.OracleDataStructOutput],
    "view"
  >;

  verify: TypedContractMethod<
    [data: IOracle.OracleDataStruct],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLatestData"
  ): TypedContractMethod<
    [dataType: BytesLike],
    [IOracle.OracleDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[data: IOracle.OracleDataStruct], [boolean], "view">;

  getEvent(
    key: "DataUpdated"
  ): TypedContractEvent<
    DataUpdatedEvent.InputTuple,
    DataUpdatedEvent.OutputTuple,
    DataUpdatedEvent.OutputObject
  >;

  filters: {
    "DataUpdated(bytes32,uint256,uint256)": TypedContractEvent<
      DataUpdatedEvent.InputTuple,
      DataUpdatedEvent.OutputTuple,
      DataUpdatedEvent.OutputObject
    >;
    DataUpdated: TypedContractEvent<
      DataUpdatedEvent.InputTuple,
      DataUpdatedEvent.OutputTuple,
      DataUpdatedEvent.OutputObject
    >;
  };
}
