/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ISecurityToken {
  export type DocumentStruct = {
    uri: string;
    documentHash: BytesLike;
    updatedAt: BigNumberish;
  };

  export type DocumentStructOutput = [
    uri: string,
    documentHash: string,
    updatedAt: bigint
  ] & { uri: string; documentHash: string; updatedAt: bigint };
}

export interface ISecurityTokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeOperator"
      | "authorizeOperatorByPartition"
      | "balanceOfByPartition"
      | "canTransferByPartition"
      | "controllerRedeem"
      | "controllerTransfer"
      | "getDocument"
      | "isOperator"
      | "isOperatorForPartition"
      | "issueByPartition"
      | "issuer"
      | "operatorTransferByPartition"
      | "partitionsOf"
      | "pause"
      | "redeemByPartition"
      | "revokeOperator"
      | "revokeOperatorByPartition"
      | "setDocument"
      | "tokenType"
      | "totalPartitions"
      | "transferByPartition"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ControllerTransfer"
      | "DocumentUpdated"
      | "Issued"
      | "IssuedByPartition"
      | "RedeemedByPartition"
      | "Revoked"
      | "TransferByPartition"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeOperatorByPartition",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfByPartition",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canTransferByPartition",
    values: [AddressLike, AddressLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "controllerRedeem",
    values: [AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "controllerTransfer",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDocument",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperator",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isOperatorForPartition",
    values: [BytesLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueByPartition",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "issuer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "operatorTransferByPartition",
    values: [
      BytesLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "partitionsOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "redeemByPartition",
    values: [BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeOperatorByPartition",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDocument",
    values: [BytesLike, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tokenType", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalPartitions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferByPartition",
    values: [BytesLike, AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "authorizeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeOperatorByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canTransferByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllerRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "controllerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isOperator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isOperatorForPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issuer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operatorTransferByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partitionsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "redeemByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeOperatorByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDocument",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tokenType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPartitions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferByPartition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace ControllerTransferEvent {
  export type InputTuple = [
    controller: AddressLike,
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish,
    data: BytesLike,
    operatorData: BytesLike
  ];
  export type OutputTuple = [
    controller: string,
    from: string,
    to: string,
    value: bigint,
    data: string,
    operatorData: string
  ];
  export interface OutputObject {
    controller: string;
    from: string;
    to: string;
    value: bigint;
    data: string;
    operatorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DocumentUpdatedEvent {
  export type InputTuple = [
    name: BytesLike,
    uri: string,
    documentHash: BytesLike
  ];
  export type OutputTuple = [name: string, uri: string, documentHash: string];
  export interface OutputObject {
    name: string;
    uri: string;
    documentHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuedEvent {
  export type InputTuple = [
    to: AddressLike,
    tokenId: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [to: string, tokenId: bigint, reason: string];
  export interface OutputObject {
    to: string;
    tokenId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IssuedByPartitionEvent {
  export type InputTuple = [
    partition: BytesLike,
    to: AddressLike,
    value: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    partition: string,
    to: string,
    value: bigint,
    data: string
  ];
  export interface OutputObject {
    partition: string;
    to: string;
    value: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedeemedByPartitionEvent {
  export type InputTuple = [
    partition: BytesLike,
    from: AddressLike,
    value: BigNumberish,
    data: BytesLike
  ];
  export type OutputTuple = [
    partition: string,
    from: string,
    value: bigint,
    data: string
  ];
  export interface OutputObject {
    partition: string;
    from: string;
    value: bigint;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevokedEvent {
  export type InputTuple = [
    from: AddressLike,
    tokenId: BigNumberish,
    reason: BytesLike
  ];
  export type OutputTuple = [from: string, tokenId: bigint, reason: string];
  export interface OutputObject {
    from: string;
    tokenId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferByPartitionEvent {
  export type InputTuple = [
    partition: BytesLike,
    operator: AddressLike,
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish,
    data: BytesLike,
    operatorData: BytesLike
  ];
  export type OutputTuple = [
    partition: string,
    operator: string,
    from: string,
    to: string,
    value: bigint,
    data: string,
    operatorData: string
  ];
  export interface OutputObject {
    partition: string;
    operator: string;
    from: string;
    to: string;
    value: bigint;
    data: string;
    operatorData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ISecurityToken extends BaseContract {
  connect(runner?: ContractRunner | null): ISecurityToken;
  waitForDeployment(): Promise<this>;

  interface: ISecurityTokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizeOperatorByPartition: TypedContractMethod<
    [partition: BytesLike, operator: AddressLike],
    [void],
    "nonpayable"
  >;

  balanceOfByPartition: TypedContractMethod<
    [partition: BytesLike, holder: AddressLike],
    [bigint],
    "view"
  >;

  canTransferByPartition: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      partition: BytesLike,
      value: BigNumberish,
      data: BytesLike
    ],
    [
      [string, string, string] & {
        statusCode: string;
        reasonCode: string;
        partition_: string;
      }
    ],
    "view"
  >;

  controllerRedeem: TypedContractMethod<
    [
      holder: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  controllerTransfer: TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getDocument: TypedContractMethod<
    [name: BytesLike],
    [ISecurityToken.DocumentStructOutput],
    "view"
  >;

  isOperator: TypedContractMethod<
    [operator: AddressLike, holder: AddressLike],
    [boolean],
    "view"
  >;

  isOperatorForPartition: TypedContractMethod<
    [partition: BytesLike, operator: AddressLike, holder: AddressLike],
    [boolean],
    "view"
  >;

  issueByPartition: TypedContractMethod<
    [
      partition: BytesLike,
      holder: AddressLike,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  issuer: TypedContractMethod<[], [string], "view">;

  operatorTransferByPartition: TypedContractMethod<
    [
      partition: BytesLike,
      from: AddressLike,
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  partitionsOf: TypedContractMethod<[holder: AddressLike], [string[]], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  redeemByPartition: TypedContractMethod<
    [partition: BytesLike, value: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  revokeOperator: TypedContractMethod<
    [operator: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeOperatorByPartition: TypedContractMethod<
    [partition: BytesLike, operator: AddressLike],
    [void],
    "nonpayable"
  >;

  setDocument: TypedContractMethod<
    [name: BytesLike, uri: string, documentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  tokenType: TypedContractMethod<[], [bigint], "view">;

  totalPartitions: TypedContractMethod<[], [string[]], "view">;

  transferByPartition: TypedContractMethod<
    [
      partition: BytesLike,
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizeOperatorByPartition"
  ): TypedContractMethod<
    [partition: BytesLike, operator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOfByPartition"
  ): TypedContractMethod<
    [partition: BytesLike, holder: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "canTransferByPartition"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      partition: BytesLike,
      value: BigNumberish,
      data: BytesLike
    ],
    [
      [string, string, string] & {
        statusCode: string;
        reasonCode: string;
        partition_: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "controllerRedeem"
  ): TypedContractMethod<
    [
      holder: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "controllerTransfer"
  ): TypedContractMethod<
    [
      from: AddressLike,
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDocument"
  ): TypedContractMethod<
    [name: BytesLike],
    [ISecurityToken.DocumentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOperator"
  ): TypedContractMethod<
    [operator: AddressLike, holder: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isOperatorForPartition"
  ): TypedContractMethod<
    [partition: BytesLike, operator: AddressLike, holder: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueByPartition"
  ): TypedContractMethod<
    [
      partition: BytesLike,
      holder: AddressLike,
      value: BigNumberish,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "issuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "operatorTransferByPartition"
  ): TypedContractMethod<
    [
      partition: BytesLike,
      from: AddressLike,
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike,
      operatorData: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "partitionsOf"
  ): TypedContractMethod<[holder: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "redeemByPartition"
  ): TypedContractMethod<
    [partition: BytesLike, value: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeOperator"
  ): TypedContractMethod<[operator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeOperatorByPartition"
  ): TypedContractMethod<
    [partition: BytesLike, operator: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDocument"
  ): TypedContractMethod<
    [name: BytesLike, uri: string, documentHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenType"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalPartitions"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "transferByPartition"
  ): TypedContractMethod<
    [
      partition: BytesLike,
      to: AddressLike,
      value: BigNumberish,
      data: BytesLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "ControllerTransfer"
  ): TypedContractEvent<
    ControllerTransferEvent.InputTuple,
    ControllerTransferEvent.OutputTuple,
    ControllerTransferEvent.OutputObject
  >;
  getEvent(
    key: "DocumentUpdated"
  ): TypedContractEvent<
    DocumentUpdatedEvent.InputTuple,
    DocumentUpdatedEvent.OutputTuple,
    DocumentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Issued"
  ): TypedContractEvent<
    IssuedEvent.InputTuple,
    IssuedEvent.OutputTuple,
    IssuedEvent.OutputObject
  >;
  getEvent(
    key: "IssuedByPartition"
  ): TypedContractEvent<
    IssuedByPartitionEvent.InputTuple,
    IssuedByPartitionEvent.OutputTuple,
    IssuedByPartitionEvent.OutputObject
  >;
  getEvent(
    key: "RedeemedByPartition"
  ): TypedContractEvent<
    RedeemedByPartitionEvent.InputTuple,
    RedeemedByPartitionEvent.OutputTuple,
    RedeemedByPartitionEvent.OutputObject
  >;
  getEvent(
    key: "Revoked"
  ): TypedContractEvent<
    RevokedEvent.InputTuple,
    RevokedEvent.OutputTuple,
    RevokedEvent.OutputObject
  >;
  getEvent(
    key: "TransferByPartition"
  ): TypedContractEvent<
    TransferByPartitionEvent.InputTuple,
    TransferByPartitionEvent.OutputTuple,
    TransferByPartitionEvent.OutputObject
  >;

  filters: {
    "ControllerTransfer(address,address,address,uint256,bytes,bytes)": TypedContractEvent<
      ControllerTransferEvent.InputTuple,
      ControllerTransferEvent.OutputTuple,
      ControllerTransferEvent.OutputObject
    >;
    ControllerTransfer: TypedContractEvent<
      ControllerTransferEvent.InputTuple,
      ControllerTransferEvent.OutputTuple,
      ControllerTransferEvent.OutputObject
    >;

    "DocumentUpdated(bytes32,string,bytes32)": TypedContractEvent<
      DocumentUpdatedEvent.InputTuple,
      DocumentUpdatedEvent.OutputTuple,
      DocumentUpdatedEvent.OutputObject
    >;
    DocumentUpdated: TypedContractEvent<
      DocumentUpdatedEvent.InputTuple,
      DocumentUpdatedEvent.OutputTuple,
      DocumentUpdatedEvent.OutputObject
    >;

    "Issued(address,uint256,bytes32)": TypedContractEvent<
      IssuedEvent.InputTuple,
      IssuedEvent.OutputTuple,
      IssuedEvent.OutputObject
    >;
    Issued: TypedContractEvent<
      IssuedEvent.InputTuple,
      IssuedEvent.OutputTuple,
      IssuedEvent.OutputObject
    >;

    "IssuedByPartition(bytes32,address,uint256,bytes)": TypedContractEvent<
      IssuedByPartitionEvent.InputTuple,
      IssuedByPartitionEvent.OutputTuple,
      IssuedByPartitionEvent.OutputObject
    >;
    IssuedByPartition: TypedContractEvent<
      IssuedByPartitionEvent.InputTuple,
      IssuedByPartitionEvent.OutputTuple,
      IssuedByPartitionEvent.OutputObject
    >;

    "RedeemedByPartition(bytes32,address,uint256,bytes)": TypedContractEvent<
      RedeemedByPartitionEvent.InputTuple,
      RedeemedByPartitionEvent.OutputTuple,
      RedeemedByPartitionEvent.OutputObject
    >;
    RedeemedByPartition: TypedContractEvent<
      RedeemedByPartitionEvent.InputTuple,
      RedeemedByPartitionEvent.OutputTuple,
      RedeemedByPartitionEvent.OutputObject
    >;

    "Revoked(address,uint256,bytes32)": TypedContractEvent<
      RevokedEvent.InputTuple,
      RevokedEvent.OutputTuple,
      RevokedEvent.OutputObject
    >;
    Revoked: TypedContractEvent<
      RevokedEvent.InputTuple,
      RevokedEvent.OutputTuple,
      RevokedEvent.OutputObject
    >;

    "TransferByPartition(bytes32,address,address,address,uint256,bytes,bytes)": TypedContractEvent<
      TransferByPartitionEvent.InputTuple,
      TransferByPartitionEvent.OutputTuple,
      TransferByPartitionEvent.OutputObject
    >;
    TransferByPartition: TypedContractEvent<
      TransferByPartitionEvent.InputTuple,
      TransferByPartitionEvent.OutputTuple,
      TransferByPartitionEvent.OutputObject
    >;
  };
}
