/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InvestorCompliance } from "./InvestorCompliance";
export type { PermissiveCompliance } from "./PermissiveCompliance";
