/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { InvestorCompliance__factory } from "./InvestorCompliance__factory";
export { PermissiveCompliance__factory } from "./PermissiveCompliance__factory";
